### ISSUE TITLE
[Enhancement]: Upgrade Android Studio to version patch 2

### ISSUE THREAD

**Issue by carlaopereirasanca** [snapcrafters/android-studio#100]
### What changes would you like?

The version of Android Studio in snap is Bumblebee patch 1. But "outside" snap, the last version is patch 2.

**Comment by abderahimali** [comment]
how to resolve the path problem of Android studio installed by Snap ?

**Comment by merlijn-sebrechts** [comment]
This has been fixed for a while now, thanks for reporting this!
