### ISSUE TITLE
[Enhancement]: Android Studio v2021.3.1

### ISSUE THREAD

**Issue by seljad** [snapcrafters/android-studio#102]
### What changes would you like?

Android Studio - Dolphin | 2021.3.1 is available on [developer.android.com](https://developer.android.com/studio). Please update android studio in the snap store to the last version.

**Comment by om26er** [comment]
@seljad I just triggered the build and it should be available in the `edge` channel soon. Please give that a spin and we can move that to stable

**Comment by merlijn-sebrechts** [comment]
This is now in stable, thank @seljad and @om26er!
