### ISSUE TITLE
[Enhancement]: update android studio Flamingo to 2022.2.1.20

### ISSUE THREAD

**Issue by Corona21** [snapcrafters/android-studio#107]
### What changes would you like?

Currently, version2022.2.1.19 is available in snap

but 2022.2.1.20 has been released end of May

Would it be possible to have it in snap?

### Any extra information?

Note: sorry, I am new to snap, and I don't know how updates are managed

The android project I am working on is used on Linux and Windows, so it would be great to have exactly the same version on both platforms (without of having to downgrade on Windows :) )
Thanks

**Comment by popey** [comment]
This can now be closed

**Comment by Corona21** [comment]
Thanks
