### ISSUE TITLE
[Enhancement]: Update to Android Studio 2022.3.1.20

### ISSUE THREAD

**Issue by rodtell** [snapcrafters/android-studio#108]
### What changes would you like?

Update to latest patch.

### Any extra information?

It is quite behind, since the available snap is 2022.3.1.18

**Comment by popey** [comment]
Someone on who has access to the snap needs to login to the store and hit the 'build' button. @kenvandine?

**Comment by lucyllewy** [comment]
I've promoted 2022.3.1.20 to stable.
