### ISSUE TITLE
[Snap store page] Please tell us the animal names

### ISSUE THREAD

**Issue by mcclure** [snapcrafters/android-studio#110]
### What changes would you like?

When I go to the snap store and look at "Channel", I see the offered version is "latest/stable 2022.3.1.20". 
Problem: I don't know what that is! The Android developers I know, we do not call Android versions by their version numbers. We call them by their codenames, which are all animals.

[<img width=260 src="https://github.com/snapcrafters/android-studio/assets/277318/cd7f232c-be50-4050-a387-a5ca52fc002a">](https://github.com/snapcrafters/android-studio/assets/277318/cd7f232c-be50-4050-a387-a5ca52fc002a)

On my project we have an agreement that we are currently using Flamingo. What version number is that? I don't know. On Windows I open the Jetbrains Toolbox app and in the list of IDEs to download "Flamingo 2022.2.1 Patch 1". I know it sounds silly but it really does say"Flamingo" in the downloader. And it is easier to remember the name "Flamingo" than the number 2022.2.

I recommend you explain, ideally in the channel name/channel popup menu but if not there in the description, what the "animal name" of the release we are about to download is.

Screenshot (expected behavior: animals. observed behavior: no animals ☹) :
![image](https://github.com/snapcrafters/android-studio/assets/277318/8f8c888e-1a19-45e4-a277-250e6e126caf)

### Any extra information?

It would also be nice to [do as suggested here](https://github.com/snapcrafters/android-studio/issues/43) and offer more than one "animal" at a time.  You installed Giraffe so this may actually create a problem when I edit our Flamingo project. I might have to be careful not to check my Giraffe-updated project files into git.

**Comment by popey** [comment]
Thanks for the suggestion @mcclure ! This is a great idea. We're currently scraping the page for the latest release, and yoinking that from the Google cdn. We could scrape the archive URL, grab any new package, build and upload to the edge channel. Then, someone can release them to named tracks. If someone wants the latest they can get latest/stable, but if they want a named version, they could get that too. 

Will need to think about this a bit, as there's a couple of technical issues with this, but they're not insurmountable. We have an in-person sprint in a couple of weeks, we'll hash it out there.

**Comment by mcclure** [comment]
@popey , that makes sense and would be helpful for my use case!

However, I do want to be clear that it would *also* improve the first-install experience just to somewhere on the Snap page, even the description, note what *the current "animal name" is for the currently shipping edge and stable. Even a user who acknowledges they're going to be getting updates might want to know which update they will *start with*. And this would be a lower-workload task than introducing new channels.

(Of course, if your channel options in the channel menu were: latest/edge, latest/stable, and then a series of channels for currently supported specific versions, the user could also get this information by looking in the channel menu and seeing which year number matches the current version in which animal-name channel.)
