### ISSUE TITLE
[Enhancement]: Update package with Android Studio Hedgehog 2023.1.1

### ISSUE THREAD

**Issue by Jackenmen** [snapcrafters/android-studio#114]
### What changes would you like?

Android Studio Hedgehog 2023.1.1 is already available:
https://developer.android.com/studio/index.html

In the Canary channel, there's also Android Studio Iguana 2023.2.1 available, not sure if that's something of interest to you.

### Any extra information?

Is there any reason the release process isn't automated (e.g. with https://github.com/snapcrafters/ci)?

**Comment by soumyaDghosh** [comment]
Done with #115 & #116
