### ISSUE TITLE
[Bug]: Android studio is closing

### ISSUE THREAD

**Issue by CesarSoftDevelopment** [snapcrafters/android-studio#131]
### What happened?

Android studio is closing with iguana version

### What should have happened?

Always

### Output of `snap info $snap_name`

```shell
Any
```

### Output of `snap connections $snap_name`

```shell
Any
```

### Output of `snap version`

```shell
Any
```

### Relevant log output

```shell
Any
```

### Teminal output of app

```shell
Any
```

**Comment by popey** [comment]
Thanks for reporting an issue. The lack of detail makes it impossible to debug what's happening.
