### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 2dengine** [snapcrafters/android-studio#137]
### What happened?

Crashed

### What should have happened?

I expected to be able to create a new "hello world" project.
Android Studio on Ubuntu is hands down the worst IDE I have ever used in my life.

### Output of `snap info $snap_name`

```shell
No
```

### Output of `snap connections $snap_name`

```shell
No
```

### Output of `snap version`

```shell
No
```

### Relevant log output

```shell
No
```

### Teminal output of app

```shell
No
```

**Comment by lengau** [comment]
Hi - I've not been able to reproduce this on my own machine. Unfortunately, without the information you have withheld, I'm not sure how to further investigate this issue. Please feel free to reopen this and provide more details.
