### ISSUE TITLE
Make Android Studio installable using Ubuntu Software

### ISSUE THREAD

**Issue by AsciiWolf** [snapcrafters/android-studio#14]
The Android Studio snap currently cannot be found in Ubuntu Software, please consider fixing this.

**Comment by om26er** [comment]
We will soon move Android Studio from 'candidate' channel to 'stable' though I am not sure if Ubuntu Software is able to install class snaps without a hassle. Maybe @popey knows.

**Comment by popey** [comment]
Known bug. https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/1690280

**Comment by AsciiWolf** [comment]
@popey I am trying this on Ubuntu 18.04 where this bug should already be fixed.

**Comment by om26er** [comment]
@popey there are many classic snaps that I can see in Ubuntu Software but Android Studio does not appear there. Anything specific that we need to do our packaging to get that fixed ?

Also the above issue you linked seems fixed already.

**Comment by popey** [comment]
@om26er yeah, that's odd. Any chance you can file a bug in gnome-software on launchpad that it can't be found?

**Comment by AsciiWolf** [comment]
@popey Are you sure that this is a GNOME Software issue?
