### ISSUE TITLE
set ANDROID_HOME for gradle to find SDK

### ISSUE THREAD

**Issue by abitrolly** [snapcrafters/android-studio#21]
I am not sure if non-snap version does this, but it makes sense to setup ANDROID_HOME when SDK is installed, so that other programs like `gradle` can find it. Example

```
./gradlew

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with sdk.dir in the local.properties file or
with an ANDROID_HOME environment variable.
```

**Comment by abitrolly** [comment]
I am running it as `ANDROID_HOME=~/Android/Sdk ` now. `~/Android/Sdk` exists outside of snap, but I don't remember - isn't it `android-studio` who downloaded and placed SDK there?

**Comment by om26er** [comment]
While android studio downloads the sdk, to make the sdk "readable" by other programs you have to export that variable yourself.

**Comment by VGerris** [comment]
in your shell rc file add :
export ANDROID_HOME=$HOME/Library/Android/sdk && export PATH=$PATH:$ANDROID_HOME/emulator && export PATH=$PATH:$ANDROID_HOME/platform-tools
