### ISSUE TITLE
Move away from external scripts to bump versions

### ISSUE THREAD

**Issue by popey** [snapcrafters/android-studio#23]
We are trying to move all the snapcrafters snaps to automatically determine (at build time) what release of upstream project they should build a snap for. For example with the [atom snap](https://github.com/snapcrafters/atom/blob/master/snap/snapcraft.yaml) we use an `install:` section to determine the version number from the upstream deb. 

I note @om26er that you're using a simple python script to do this external to the build. Can this please be integrated as we have with Atom and Discord within the yaml?

That way, when build.snapcraft.io does a build, we know it's the latest release in the edge channel, and can start testing that without having to keep editing or committing to this branch.

**Comment by popey** [comment]
build will trigger one build every day, it already does this for snaps which were recently hooked up to the build service. So once the changes are made, we'll get daily builds by default.

**Comment by om26er** [comment]
@popey I proposed something here https://github.com/snapcrafters/android-studio/pull/25
