### ISSUE TITLE
Not getting updated to 3.1.4

### ISSUE THREAD

**Issue by adityanaique** [snapcrafters/android-studio#33]
Hi,
I noticed that the 3.1.4 release has already been merged two days ago but I'm still stuck with 3.1.3. I removed the snap and reinstalled it, but I again got 3.1.3. Is this normal? Does it take time for the updates to reach us after getting merged?
I checked the versions of my other installed snap packages by visiting their respective websites. All of them are up-to-date. Issue is only with AS. I'm on Ubuntu 18.04.1 LTS, by the way.

**Comment by popey** [comment]
Thanks for the report @adityanaique - apologies for the delay. I wanted to do some additional testing first. I've now done this and pushed 3.1.4 to the stable channel.
