### ISSUE TITLE
connecting to google account

### ISSUE THREAD

**Issue by guyluz11** [snapcrafters/android-studio#37]
When trying to connect to google account the following massage appears:
"Unable to create io-slave. Can not create socket for launching io-slave for protocol 'https'."

How to reproduce:
In the upper right side of the screen there is white button with person simbol on it,
Click on the button and popup will appear, than click on  Sign In  and you will get the error .

Android studio version 3.2
snap version 3.2.0.26 stable

**Comment by om26er** [comment]
seems you are using KDE ? Please set the default app to your working web browser (Firefox or anything) in default applications.

The issue is most likely unrelated to the snap, its probably a KDE bug.

**Comment by popey** [comment]
I just tested this on KDE Neon. It launched my default browser - Firefox (the snap) and it launched the Google login process. I logged in successfully and now have my avatar in the top right corner of Android Studio.

**Comment by om26er** [comment]
It doesnt happen always or for everyone, though I have faced that prevously, on multiple ocassions and setting the default app fixes it. So basically in some cases the default app is set to "none" even though the required app is already installed.

**Comment by guyluz11** [comment]
I deleted the snap and installed it from the android studio site and it worked right away.
And you are right, I don't have no default app for web browser.
 
Thank you.

**Comment by popey** [comment]
Thanks for letting us know @guyluz11
