### ISSUE TITLE
Android studio cannot launch

### ISSUE THREAD

**Issue by diksub26** [snapcrafters/android-studio#41]

**Comment by popey** [comment]
Did you put that in `$HOME/.AndroidStudio3.2/config/studio64.vmoptions`? I tried a number of options and it works fine here. I even over-allocated, way more RAM than I have and it still launches fine. Maybe comment out the changed lines in that file and see if it's some other issue? Then maybe add the line back in to confirm it really is that line causing the issue? How much RAM and Swap does your system have?

**Comment by dikisubagja** [comment]
thanks now can run.. after I delete the comment "<---- increase this to most of your RAM '.
but now, i have now error message. this the error message

OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0

(java:2597): Gdk-CRITICAL **: 18:57:30.109: IA__gdk_x11_display_get_xdisplay: assertion 'GDK_IS_DISPLAY (display)' failed
Gtk-Message: 18:57:30.220: Failed to load module "canberra-gtk-module"
Jan 14, 2019 6:57:49 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
How to fix it ?

my ram 8gb and my swap 16gb

**Comment by om26er** [comment]
I think you can ignore those issues, those warnings are independent of this snap package.
