### ISSUE TITLE
Android Studio 3.4

### ISSUE THREAD

**Issue by VolkerSchiewe** [snapcrafters/android-studio#50]
Please update to the latest version :)

Is it may possible to trigger the update myself or having an automatic upgrade?

**Comment by popey** [comment]
Thanks for the notification!

It's easier for us to trigger it, which I have just done. You can see the build status at https://launchpad.net/~build.snapcraft.io/+snap/125825f60ca4a81dbf25024d40e45f87 - once complete it'll be in the edge channel. If you refresh to the edge channel `snap refresh android-studio --edge` you'll get it soon after it publishes. Alternatively wait for me to push it to stable a little later. :)

**Comment by popey** [comment]
Welp, that failed. Looks like the magic scraping of the web page which pulls out the linux zip file is failing. @om26er thoughts? :)

**Comment by om26er** [comment]
@popey, yes Google was previously shipping a zip file, now they ship a tar.gz, this should fix that https://github.com/snapcrafters/android-studio/pull/51

**Comment by popey** [comment]
Your fix worked, thanks @om26er .

3.4 is now in stable. Thanks again @VolkerSchiewe
