### ISSUE TITLE
Virtual devices are not found

### ISSUE THREAD

**Issue by sketchbuch** [snapcrafters/android-studio#53]
I have several virtual devices created and the device drop down always shows that "no devices found". This only happens with the snap version of androids studio, if I download the latest version from the official website, extract it and start androidstudio the virtual device selector shows all my devices. I'd rather use the snap version as it seems faster to start but it's annoying having to open the AVD manager and manually start a device first.

**Comment by ciscorucinski** [comment]
Can you check #54 to see if you have the required libraries installed?

**Comment by merlijn-sebrechts** [comment]
Closing this issue due to the lack of response. This was possibly because the required libraries were not installed. Please reopen if this was not the case!
