### ISSUE TITLE
Error in console when emulator is launched

### ISSUE THREAD

**Issue by gundesli** [snapcrafters/android-studio#56]
In Ubuntu version 18.04.2, when the emulator is launched there is this error in console:
Emulator: Warning: QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.android-studio', please create it with 0700 permissions. ((null):0, (null))

**Comment by ShohanAhmed** [comment]
Same problem. Please fix it.

**Comment by om26er** [comment]
Should be fixed by https://github.com/snapcrafters/android-studio/pull/74
