### ISSUE TITLE
Native file watcher is not executable 

### ISSUE THREAD

**Issue by unicyn** [snapcrafters/android-studio#6]
When I tried to run for the first I got this error:
21:28	External file changes sync may be slow: Native file watcher is not executable: /snap/android-studio/21/android-studio/bin/fsnotifier64

  - android-studio
tracking:    edge
installed:   3.0.0.18 (21) 679MB classic
refreshed:   2017-11-18 20:05:39 +0100 CET

**Comment by om26er** [comment]
Thanks for the bug report. We are aware of the issue, basically same as https://github.com/snapcrafters/android-studio/issues/2

**Comment by om26er** [comment]
This is now fixed. Please refresh latest version.

**Comment by unicyn** [comment]
Hi,
Thanks, I don't the error.
