### ISSUE TITLE
launch time in 3.5.2 (ubuntu 19.10) 

### ISSUE THREAD

**Issue by neptu39701** [snapcrafters/android-studio#61]
launch time for the program is about 35 seconds and that's too much while launch time of google native Linux IDE is about 15 seconds is there any way to make it faster ?

**Comment by popey** [comment]
For me (ThinkPad X220 / i7 / 32GB / SSD) it takes 6 seconds to get to the splash, then 18 seconds to "Loading project" for first launch.

Second launch is 2 seconds to splash screen, 7 seconds to loading project. 

Is it slow for you on every launch?

**Comment by neptu39701** [comment]
> For me (ThinkPad X220 / i7 / 32GB / SSD) it takes 6 seconds to get to the splash, then 18 seconds to "Loading project" for first launch.
> 
> Second launch is 2 seconds to splash screen, 7 seconds to loading project.
> 
> Is it slow for you on every launch?

i use asus vivobook pro n580 (i7/16Gb/ssd) and it takes almost 31 seconds on every launch before splash screen, splash screen takes about 8  and loading project is about 20 seconds!
which linux distribution are you using right now and did you do any tweaks ?
