### ISSUE TITLE
New Version: Android Studio 3.6.2

### ISSUE THREAD

**Issue by breautek** [snapcrafters/android-studio#68]
Just posting to question when we can expect the snap repository to include version 3.6.2 or to raise awareness that a new version is now available.

https://developer.android.com/studio
https://androidstudio.googleblog.com/2020/03/android-studio-362-available.html

Thanks

**Comment by popey** [comment]
Thank you. Building now.

**Comment by popey** [comment]
Released to stable! Thanks again!
