### ISSUE TITLE
Setup CI 

### ISSUE THREAD

**Issue by om26er** [snapcrafters/android-studio#8]
We need CI for this project. The only thing that I have currently in mind is that it will just build the snap before allowing any change to get merged.

Lets use the free Travis CI, so that we don't have any dependency on Canonical. @popey thoughts ?

**Comment by popey** [comment]
Sounds like a plan. I'm fine with travis or circle-ci. In fact it might be neat to have some projects using one, and some using another, just to make sure we're exercising all the options. 

Would that be confusing, mixing things up though?

**Comment by abitrolly** [comment]
If admins enable `Travis CI ` and tell what commands need to be run, then I can send PR to close this,

**Comment by abitrolly** [comment]
On the second thought, it is better to do
```
snapcraft enable-ci travis
```
https://docs.snapcraft.io/build-snaps/ci-integration

**Comment by om26er** [comment]
Apart from making sure the snap builds, the CI process should also ensure that the sha256sum of the executable is the same as the one from upstream.

I am collecting some more scenarios and will propose something over the weekends.

**Comment by om26er** [comment]
Closing this as the CI is now enabled, thanks @popey
