### ISSUE TITLE
Missing essential plugin: org.jetbrains.android

### ISSUE THREAD

**Issue by ajcasagrande** [snapcrafters/android-studio#81]
Snap version `4.1.1.0`
OS: `Ubuntu 18.04`

```
$ snap run android-studio

2020-11-14 09:29:27,296 [    687]   WARN - llij.ide.plugins.PluginManager - Problems found loading plugins:
  The Compose (id=androidx.compose.plugins.idea, path=/snap/android-studio/97/android-studio/plugins/android-compose-ide-plugin) plugin Non-optional dependency plugin org.jetbrains.kotlin is disabled
  The Android (id=org.jetbrains.android, path=/snap/android-studio/97/android-studio/plugins/android) plugin Non-optional dependency plugin org.jetbrains.kotlin is disabled
  The App Links Assistant (id=com.google.urlassistant, path=/snap/android-studio/97/android-studio/plugins/url-assistant) plugin depends on plugin "org.jetbrains.android" that failed to load
  The Test Recorder (id=com.google.gct.test.recorder, path=/snap/android-studio/97/android-studio/plugins/test-recorder) plugin depends on plugin "org.jetbrains.android" that failed to load
  The Firebase Services (id=com.google.services.firebase, path=/snap/android-studio/97/android-studio/plugins/firebase) plugin depends on plugin "org.jetbrains.android" that failed to load
  The Firebase Services (id=com.google.services.firebase, path=/snap/android-studio/97/android-studio/plugins/firebase) plugin requires "Test Recorder" plugin to be enabled
  The Google Developers Samples (id=com.google.cluestick.studioclient, path=/snap/android-studio/97/android-studio/plugins/google-samples) plugin depends on plugin "org.jetbrains.android" that failed to load
  The Firebase App Indexing (id=com.google.appindexing, path=/snap/android-studio/97/android-studio/plugins/google-appindexing) plugin depends on plugin "org.jetbrains.android" that failed to load
  The Firebase App Indexing (id=com.google.appindexing, path=/snap/android-studio/97/android-studio/plugins/google-appindexing) plugin requires "App Links Assistant" plugin to be enabled
  The Android NDK Support (id=com.android.tools.ndk, path=/snap/android-studio/97/android-studio/plugins/android-ndk) plugin depends on plugin "org.jetbrains.android" that failed to load
  The Android APK Support (id=com.android.tools.apk, path=/snap/android-studio/97/android-studio/plugins/android-apk) plugin depends on plugin "org.jetbrains.android" that failed to load
  The Android APK Support (id=com.android.tools.apk, path=/snap/android-studio/97/android-studio/plugins/android-apk) plugin requires "Android NDK Support" plugin to be enabled
  The Firebase Testing (id=com.google.gct.testing, path=/snap/android-studio/97/android-studio/plugins/firebase-testing) plugin depends on plugin "org.jetbrains.android" that failed to load
  The Google Cloud Tools For Android Studio (id=com.google.gct, path=/snap/android-studio/97/android-studio/plugins/google-cloud-tools-as) plugin depends on plugin "org.jetbrains.android" that failed to load 
2020-11-14 09:29:27,312 [    703]  ERROR - llij.ide.plugins.PluginManager - Missing essential plugins: org.jetbrains.android 
com.intellij.ide.plugins.PluginManagerCore$EssentialPluginMissingException: Missing essential plugins: org.jetbrains.android
	at com.intellij.ide.plugins.PluginManagerCore.checkEssentialPluginsAreAvailable(PluginManagerCore.java:1638)
	at com.intellij.ide.plugins.PluginManagerCore.initializePlugins(PluginManagerCore.java:1695)
	at com.intellij.ide.plugins.PluginManagerCore.loadAndInitializePlugins(PluginManagerCore.java:1917)
	at com.intellij.ide.plugins.PluginManagerCore.lambda$initPlugins$6(PluginManagerCore.java:1319)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-11-14 09:29:27,315 [    706]  ERROR - llij.ide.plugins.PluginManager - Android Studio 4.1.1  Build #AI-201.8743.12.41.6953283 
2020-11-14 09:29:27,315 [    706]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_242-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-11-14 09:29:27,315 [    706]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 

Corrupted Installation: Missing essential plugin:

  org.jetbrains.android

Please reinstall Android Studio from scratch.

```

![image](https://user-images.githubusercontent.com/48735240/99151873-5da66f00-265b-11eb-9a11-0cf5ba92395e.png)

**Comment by ajcasagrande** [comment]
Apparently this was a system configuration issue. Somehow the kotlin plugin was disabled in my `~/.config/Google/AndroidStudio4.1/disabled_plugins.txt` file.

**Comment by chetansharma10** [comment]
How can I fix this.

**Comment by ajcasagrande** [comment]
> How can I fix this.

In my case all I had to do was open the file `~/.config/Google/AndroidStudio4.1/disabled_plugins.txt` and delete the line that referenced `Kotlin`. Note that the file path may be different based on your version of AS.

**Comment by chetansharma10** [comment]
Thanks

**Comment by Sagar-2-99** [comment]
in my mac i haven't found this file so plz help me

**Comment by chetansharma10** [comment]
The only way to fix this thing is to reinstall your os and Android studio

**Comment by Sagar-2-99** [comment]
can't we find the location where diable plugin file is located?

**Comment by spike** [comment]
> in my mac i haven't found this file so plz help me

On a mac, open your finder, type `disabled_plugins.txt` in the search box of your finder.

On my mine, it was located at MYUSERNAME > Library > Application Support > Google > AndroidStudioxx

Then just remove the line that references `org.jetbrains.kotlin`

**Comment by effiedude** [comment]
Donot deleate or disable any plugin that installed by studio

**Comment by simarjeet30** [comment]
I am getting this error even after so many reinstallations from scratch .I even deleted disable_plugin.txt file ,but still getting the same error .If anyone knows about it ,Please respond.
![image](https://user-images.githubusercontent.com/78863464/129712706-6c0bdbea-7277-4d0d-bd97-bbefb3411848.png)

**Comment by chetansharma10** [comment]
In my case i reinstall my os to fix this.Its very difficult to find the
plugin files.

**Comment by simarjeet30** [comment]
Okay thanks

**Comment by erperejildo** [comment]
I don't have any `Google` folder withing `.config`

**Comment by gargbindu** [comment]
In case of MacOS, you can find the disabled_plugins file using the command given below.

<code>find ~/Library -name disabled_plugins.txt</code>

In my case next command in terminal helped to find bad files 
<code>find ~/Library -name disabled_plugins.txt</code>

I found these files and deleted all of them and fixed the issue.

/Users/ashwanigarg/Library/Application Support/Google/AndroidStudio4.2/disabled_plugins.txt
/Users/ashwanigarg/Library/Application Support/Google/AndroidStudio4.1/disabled_plugins.txt
/Users/ashwanigarg/Library/Application Support/Google/AndroidStudio2020.3/disabled_plugins.txt

**Comment by erperejildo** [comment]
the trick for me was to run `mdfind disabled_plugins.txt` in MacOS

**Comment by om26er** [comment]
On Linux, please try if deleting `~/.config/Google/AndroidStudio*` works

**Comment by harsh0035** [comment]
only search your pc disabled_plugins.txt and open file location then disabled_plugins.txt delete

**Comment by islamideveloper** [comment]
for windows this is solv with powershell
https://youtu.be/tfU8X8UMUY8

**Comment by Kronos-2701** [comment]
> the trick for me was running `mdfind disabled_plugins.txt` on MacOS

Hey , can't find anything like that in M1 Mac . 

Help Pls.

**Comment by Link8636** [comment]
Can't find disable_plugins.txt on Windows 10

**Comment by Suyash-Purwar** [comment]
For Windows 10/11
Delete this file
C:\Users\YourUserName\AppData\Roaming\Google\AndroidStudioPreview4.X\disabled_plugins.txt

Worked fine for me!

**Comment by Gurukorgi** [comment]
mine is throwing a whole bunch of errors as follows
missing essetial plugins
com.android.tools.design
com.intelij.java
com.intelij.java,ide
org.jetbrains.android

**Comment by Maxidromm** [comment]
Have  the same issue, any help please ?
![studio eror](https://github.com/snapcrafters/android-studio/assets/75587678/4a70c447-4041-4e19-b2eb-551418b0850d)

**Comment by semedo-nob** [comment]
Delete all the fragments of the application install a new a but different
version of the application

**Comment by Maxidromm** [comment]
Will try now, Thanks !

**Comment by Maxidromm** [comment]
Will try now, thanks !

**Comment by Maxidromm** [comment]
It works yeah 👍🏻

**Comment by semedo-nob** [comment]
Glad to hear it!

**Comment by Agetachew1** [comment]
I disabled koltlin in order to have java as a default but it gave me the same error that you see above. 
1) naviate to your plugins: 
cd ~/Library/Application\ Support/Google/AndroidStudio2022.3/plugins
If you don't see Kotlin as a plugin then you need to go to jetBrains Plugin and download it and once you extract it drag and drop it in the current plugins folder. It doesn't matter if it is comparable. 
2) try opening it again if it is not working then. run this code. 
bash
rm -rf /Users/gabenezer/Library/Preferences/Google/AndroidStudio*
rm -rf /Users/gabenezer/Library/Preferences/com.google.android.studio.plist
rm -rf /Users/gabenezer/Library/Application\ Support/Google/AndroidStudio*
rm -rf /Users/gabenezer/Library/Caches/Google/AndroidStudio*
rm -rf /Users/gabenezer/Library/Logs/Google/AndroidStudio*

then try opening it again. 
This worked for me.

**Comment by semedo-nob** [comment]
Delete traces of the android studio application that's currently installed
on your PC, uninstall the android studio app, install another version of
Android studio,there are different versions from hedgehog, iguana to
giraffe

**Comment by keli-spatel** [comment]
nternal error. Please refer to https://code.google.com/p/android/issues

com.intellij.ide.plugins.PluginManagerCore$EssentialPluginMissingException: Missing essential plugins: com.android.tools.design, org.jetbrains.android
    at com.intellij.ide.plugins.PluginManagerCore.checkEssentialPluginsAreAvailable(PluginManagerCore.java:761)
    at com.intellij.ide.plugins.PluginManagerCore.initializePlugins(PluginManagerCore.java:854)
    at com.intellij.ide.plugins.PluginManagerCore.initializeAndSetPlugins(PluginManagerCore.java:1068)
    at com.intellij.ide.plugins.PluginDescriptorLoader$scheduleLoading$pluginSetDeferred$1.invokeSuspend(PluginDescriptorLoader.kt:397)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

-----
Your JRE: 17.0.7+0-b2043.56-10550314 amd64 (JetBrains s.r.o.)
C:\Program Files\Android\Android Studio\jbr

**Comment by semedo-nob** [comment]
Uninstall the android studio, delete every file fragments of it in your
machine , simply make your machine clear of that android studio version

2.Go to android studio download site there is an archive , choose a
different version of Android studio to download
( That was my resolution, I'd appreciate if you've got another)

**Comment by darshitshah8** [comment]
I worked in Flutter, and now I switch to React Native, but when I create a React Native project, kotlinversion and ndkversion are added automatically to the build.gradle file in the project. can anyone tell me how to stop adding kotlin version in my react native project?

**Comment by cuishuang** [comment]
Mac OS:

cd /Users/xxxxx/Library/Application\ Support/JetBrains/

rm -rf  XXXXX

reinstall
