### ISSUE TITLE
Android Studio 4.2.1

### ISSUE THREAD

**Issue by mirland** [snapcrafters/android-studio#86]
A new version of Android studio was released some days ago https://developer.android.com/studio/releases

**Comment by mirland** [comment]
@om26er @popey any news?

**Comment by popey** [comment]
@mirland the latest release is in the edge channel. if you `snap refresh android-studio --edge` you'll be on it. The latest build always lands there pretty quickly after upstream release. It only ever contains stable upstream builds, not canary or beta, so edge is pretty safe here, relatively speaking ;).

If it all works as expected, maybe ping @igorljubuncic and @rhys-the-davies to release it to the stable channel at their earliest convenience!

**Comment by om26er** [comment]
I missed this one earlier. Android studio 4.2.1 works as expected. Will promote that to stable channel in a bit.

**Comment by om26er** [comment]
This is done now.
