### ISSUE TITLE
Last update broke the install. This also happened in AUR package (Manjaro)

### ISSUE THREAD

**Issue by kanaida2** [snapcrafters/android-studio#89]
Corrupted Installation

Missing Essential Plugin:
org.jetbrains.android
Please re-install android studio from scratch.

![Screenshot from 2021-08-14 18-20-42](https://user-images.githubusercontent.com/55221216/129461641-85a48272-8270-4322-bc46-99a84c618851.png)

**Comment by merlijn-sebrechts** [comment]
Since this also happened in the AUR, this was probably an issue with the upstream package itself. Closing this for now. Please reopen if this was not the case!
