### ISSUE TITLE
Trigger build for 2020.3.1 Patch 2

### ISSUE THREAD

**Issue by domyn** [snapcrafters/android-studio#91]
The 2020.3.1 version available in Snap misses some important bugfixes, for example it does not allow to load plugin themes (this was fixed in Patch 1). Can you please trigger build for patch 2 (2020.3.1.24) and push it to Snap store?

**Comment by om26er** [comment]
Triggered new build, should be available in the edge channel in a few minutes. You may track the build here https://launchpad.net/~build.snapcraft.io/+snap/125825f60ca4a81dbf25024d40e45f87/+build/1529573

**Comment by domyn** [comment]
Thanks :)
