### ISSUE TITLE
Android 12 is released. kindly please add that into SDK manager. still it shows preview only

### ISSUE THREAD

**Issue by vijaywavemaker** [snapcrafters/android-studio#93]
Hi Team,

I'm using Ubuntu 18.4. Installed your andriod studio from ubuntu app store app.
Android studio Arctic Fox | built on July 27,2021

Android 12 is released. kindly please add that into SDK manager. still it shows preview only. 
If you can not add then kindly please update about the possible date of your plan to add that. Thanks a lot in advance :) 

@om26er Kindly please help on this. Thanks a lot :)

**Comment by merlijn-sebrechts** [comment]
Closing as it was an upstream issue.
