### ISSUE TITLE
Missing essential plugin: org.jetbrains.android MacBook

### ISSUE THREAD

**Issue by appletouhid** [snapcrafters/android-studio#94]
Finder/application/Select (Android Studio) Right Side (+) Click See Two Box Name and are't include. firstly, Click Name and Choose System Files than OK. Second, are included Select after this see (disabled_plugins.txt) remove this file.

**Comment by diddledani** [comment]
This repository is only the packaging as a Snap Package for Linux. We have no control over the Mac versions released by Google/JetBrains. If I'm mistaken about you running a mac then please feel free to reopen.
