### ISSUE TITLE
[Enhancement]:  android-studio Linux arm64 support

### ISSUE THREAD

**Issue by guyluz11** [snapcrafters/android-studio#98]
### What changes would you like?

I am not sure if android studio support arm64 for Linux but I would like to see this option on the snap store page.

I think now is the best time since the new mac m1 machine is arm64 and [some work is being done](https://asahilinux.org/) to run Linux on top of it.

![image](https://user-images.githubusercontent.com/9304740/153429750-594c1a97-1334-4c34-91ad-9e85fe59f0e9.png)

### Any extra information?

One user [on Reddit](https://www.reddit.com/r/AndroidStudio/comments/o9k53g/how_to_install_android_studio_on_linux_for_arm64/) said that we can download it for Linux arm64 using flatpack, so if it really exists I would love to see it in the snap option as well.

Also how to install on [Chromebook](https://www.reddit.com/r/AndroidStudio/comments/e8r9or/how_to_install_android_studio_stable_release_on/) ARM64 processor.

leaving [this](https://www.reddit.com/r/AndroidStudio/comments/q4wugw/linux_arm_possible_to_run_android_studio/) here, to post in case there is a change.

**Comment by merlijn-sebrechts** [comment]
Flathub doesn't provide an arm build either. Don't believe random people on Reddit.

```shell
$ flatpak remote-info flathub com.google.AndroidStudio --arch=aarch64
error: Error searching remote flathub: Can't find ref com.google.AndroidStudio/aarch64
$ flatpak remote-info flathub com.google.AndroidStudio --arch=arm
error: Error searching remote flathub: Can't find ref com.google.AndroidStudio/arm
$ flatpak remote-info flathub com.google.AndroidStudio --arch=x86_64
        ID: com.google.AndroidStudio
       Ref: app/com.google.AndroidStudio/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 21.5 MB
 Installed: 47.8 MB
   Runtime: org.freedesktop.Sdk/x86_64/21.08
       Sdk: org.freedesktop.Sdk/x86_64/21.08

    Commit: f6b9c8d2040a5a041ed33acfbd25cb498a238e8193e65021530ebf9041a2d6c4
    Parent: 3e2b87fafb63b42ff69f8230619aace6aa4d8c1e6f8d231ed2bd7d85dfe42f8f
   Subject: Update android-studio.tar.gz (c2ce5b82)
      Date: 2022-10-25 17:10:35 +0000
```

 Closing this as it's an upstream issue. Feel free to reopen the issue once upstream supports arm!

**Comment by guyluz11** [comment]
I am using the snap store and it does support arm.
Here is the snapstore page of android-studio https://snapcraft.io/android-studio

**Comment by diddledani** [comment]
@guyluz11 you misunderstood. While the snap store supports arm, as you rightly point out, that isn't the issue. We are packaging the Android Studio as supplied by Google, which does *not* support arm, so we cannot create an arm package of it.

**Comment by guyluz11** [comment]
Yep, so we are waiting for Android studio itself to support it.

If someone is bumping into requests for Google Android studio team to support it please paste it here so everyone can upvote it.
